### ISSUE TITLE
Image transitions?

### ISSUE THREAD

**Issue by matteoraggi** [paddywwoof/rust_pi3d#1]
Is it working to do image transition effects?

**Comment by paddywwoof** [comment]
Matteo, I've not translated the relevant demos into rust but they should work as the shaders are identical. The issue would be releasing the Texture structs once they're finished with - that's something nagging away at the back of my mind: I really ought to have a reference counting system.

But there's little point using the high execution speed of rust for things like this. Python can do it just as well and is less mind boggling!
